---
    name: "Print a secret"
    
    on:
      workflow_call:

    jobs:
      print-secret:
        runs-on: ubuntu-20.04
        steps:
          - name: Print secret, or try to
            run: |
              echo 'if there are stars here then REPO_SECRET has a value:'
              echo '-->|${{ secrets.REPO_SECRET }}|<--'
              echo 'if there are stars here then CALLER_SECRET has a value:'
              echo '-->|${{ secrets.CALLER_SECRET }}|<--'
